-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 21:15:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pipocadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipocadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipocadb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `pipocadb` ;

-- -----------------------------------------------------
-- Table `pipocadb`.`GENERO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pipocadb`.`GENERO` ;

CREATE TABLE IF NOT EXISTS `pipocadb`.`GENERO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipocadb`.`FILME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pipocadb`.`FILME` ;

CREATE TABLE IF NOT EXISTS `pipocadb`.`FILME` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(4000) NULL,
  `diretor` VARCHAR(60) NULL,
  `posterpath` VARCHAR(200) NULL,
  `popularidade` DECIMAL(10,2) NULL,
  `data_lancamento` DATE NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id`, `id_genero`),
  INDEX `fk_FILME_GENERO_idx` (`id_genero` ASC),
  CONSTRAINT `fk_FILME_GENERO`
    FOREIGN KEY (`id_genero`)
    REFERENCES `pipocadb`.`GENERO` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insere os generos
-- -----------------------------------------------------
insert into genero (id, nome) values 
(28, 'Ação'),
(12, 'Aventura'),
(16, 'Animação'),
(35, 'Comédia'),
(80, 'Crime'),
(99, 'Documentário'),
(18, 'Drama'),
(10751, 'Família'),
(14, 'Fantasia'),
(36, 'História'),
(27, 'Horror'),
(10402, 'Musical'),
(9648, 'Mistério'),
(10749, 'Romance'),
(878, 'Ficção Científica'),
(10770, 'Filme para TV'),
(53, 'Suspense'),
(10752, 'Guerra'),
(37, 'Western');

insert into filme (id, titulo, descricao, diretor, posterpath, popularidade, data_lancamento, id_genero) values
(1, 'O Náufrago', 'O Náufrago' , 'Robert Zemeckis' ,'img/naufrago.jpg' , 50 , STR_TO_DATE('26-01-2001', '%d-%m-%Y'), 28),
(2, 'Os Incríveis', 'Os Incríveis' , 'Brad Bird' ,'img/incriveis.jpg' ,65 , STR_TO_DATE('10-12-2004', '%d-%m-%Y'), 12),
(3, 'Star Wars - O Último Jedi', 'Star Wars - O Último Jedi' , 'Rian Johnson' ,'img/starwars.jpg' ,85 , STR_TO_DATE('14-12-2017', '%d-%m-%Y'), 878),
(4, 'O Senhor dos Aneis - O Retorno do Rei', 'O Senhor dos Aneis - O Retorno do Rei' , 'Peter Jackson' ,'img/senhordosaneis.jpg' ,80 , STR_TO_DATE('25-12-2003', '%d-%m-%Y'), 28),
(5, 'Carros 2', 'Carros 2' , 'John Lasseter' ,'img/cars2.jpg' ,45 , STR_TO_DATE('23-06-2011', '%d-%m-%Y'), 10751),
(6, 'Harry Potter e as Relíquias da Morte - Parte 2', 'Harry Potter e as Relíquias da Morte - Parte 2' , 'J. K. Rowling' ,'img/hp.jpg' ,85 , STR_TO_DATE('15-07-2011', '%d-%m-%Y'), 28);